[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py
addopts =
    -ra
    --cov=accounts
    --cov=summaries
    --cov-report=term-missing
    --cov-report=xml
    --cov-fail-under=90
